### ISSUE TITLE
Sparky docker with plugins

### ISSUE THREAD

**Issue by spigell** [melezhik/sparky-docker#2]
Здравствуйте. Вы планируете в новой версии этого докера добавить поддержку (установку) плагинов? Может быть в mountpoint.sh это добавить?

**Comment by melezhik** [comment]
Приветствую! Извините, что вы имеет ввиду? Впринципе установка плагинов может быть через
`docker exec zef install $Sparky-Plugin` на запущенном докер контейнере ( конечно для этого мне еужно будет собрать новый image с последней версией Sparky ), или вы знаете как это сделать по-другому?

**Comment by spigell** [comment]
Здравствуйте. Я имел ввиду скрипт entrypoint.sh. То есть можно было бы при запуске докера устанавливать модули из списка (файл plugins_list) в корне. Это конечно увеличить время загрузки докера, потому что модули довольно долго ставятся и проверяются.
Докер конечно нужно пересобирать новый, да.

**Comment by melezhik** [comment]
Я понял, в принципе идея мне нравится. Только нужно что бы файл plugin_list был доступен докер инстансу на чтение , куда вы его предлагаете проложить ? В папку $Sparky-root ?

**Comment by spigell** [comment]
Как вариант, да. Рядом с сценариями.

**Comment by melezhik** [comment]
я почти закончил рефакторинг Dockerfile и даже залил новый image в dockerhub, осталось добавить поддержку установки Sparky плагинов при запуске контейнера.

**Comment by spigell** [comment]
Да, спасибо. Но там все еще нет ssh.=)

У вас есть идея насчет установки дополнительных модулей? 

Кроме того, могу ошибаться, но заметил, что многие модули полагаются на системные зависимости. Например, SSL модуль требует openssl пакет (openssl-dev для прохождения тестов)? Поэтому просто сделать устанавливать модули из списка возможно через zef будет недостаточно - некоторые в принципе не смогут установится. 
Пока мне думается, можно добавить в entrypoint.sh 
```
if [[ -d /tmp/entrypoint.d ]]; then
  for f in /tmp/entrypoint.d/* ;do
    source $f
  done
fi
```
И в каталоге entrypoint.d, который монтируется с хоста, накидывать что надо сделать с контейнером после поднятия.
Или делать это уже с помощью других служб (sparrowdo к примеру) уже после поднятия.

**Comment by melezhik** [comment]
Здравствуйте!

По вашим комментариям

1. добавил в docker sparky пакет openssh-client (  я так понимаю нужен, что бы запускать sparky/sparrowdo задачи на других хостах по ssh ? ), если нужен все-таки на sparky докер контейнере нужен ssh сервер - то скажите я -  я могу добавить

2. ввел понятие ***runtime setup*** для Sparky докер контейнера - решает ваши задачи по дополнительной настройке и провизонингу запускаемого sparky контейнера. Все, что вам нужно - это создать sparrowfile файл в папке `$sparky-root/sparky-setup`, и он будет запущен, через entrypoint при запуске sparky docker контейнера:

```
$ cat $sparky-root/sparky-setup/sparrowfile

package-install 'open-ssl';
zef 'Sparky::Plugin::Notify::Telegram', %( notest => True );
zef ' Sparky::Plugin::Notify::Email', %( notest => True );
# so on ...


```

Далее запускаем контейнер:

```
$ docker run -d -v $sparky-root:/home/sparky/.sparky/projects -p 3000:3000 melezhik/sparky
```

`$sparky-root/sparky-setup/sparrowfile` будет запущен в начале.

Все это задокументировано здесь - https://github.com/melezhik/sparky-docker#sparky-runtime-setup

**Comment by melezhik** [comment]
обновил image на https://hub.docker.com/r/melezhik/sparky/ , пробуйте ...

**Comment by spigell** [comment]
Спасибо большое! Попробую. 
Только на alpine нет пакета open-ssl. Есть openssl и openssl-dev.

**Comment by spigell** [comment]
> добавил в docker sparky пакет openssh-client ( я так понимаю нужен, что бы запускать sparky/sparrowdo задачи на других хостах по ssh ? ), если нужен все-таки на sparky докер контейнере нужен ssh сервер - то скажите я - я могу добавить


Да, нужен только клиент, чтобы из коробки можно было запускать на удаленных хостах.

**Comment by spigell** [comment]
Проверил. Работает.

**Comment by melezhik** [comment]
Отлично. )))
