### ISSUE TITLE
ssh: command not found

### ISSUE THREAD

**Issue by spigell** [melezhik/sparky-docker#3]
Здравствуйте. Давайте в докер добавим пакет openssh, раз sparrowdo использует ssh.
`apk add openssh`

**Comment by melezhik** [comment]
Согалсен. Я думаю, что в ближайшее время пересобиру имидж, что бы там была последняя версия Sparky со всеми новыми фичами, включу туда установку пакета openssh

**Comment by melezhik** [comment]
закрываю в пользу #2 - решается, обсуждается там.
