### ISSUE TITLE
Where is bootstrap.sh ?

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky-docker#8]
[Referenced in Dockerfile](https://github.com/melezhik/sparky-docker/blob/master/Dockerfile#L4), I can't find bootstrap.sh file : sparrowhub.org seems "under construction" and sparrowhub.io/bootstrap.sh does not exist.

**Comment by melezhik** [comment]
The Dockerfile is outdated and needs to be changed, I'll take a look at this ...

**Comment by melezhik** [comment]
I think we need to update Dockerfile not only in terms of this issue, but make it uptodate with the latest Rakudo images, which  supported by @JJ - https://github.com/JJ/alpine-raku

**Comment by melezhik** [comment]
@thibaultduponchelle  I decided to completely rewrite existing Dockerfile, it works for me now, please test. Updates:


* `Sparkyd` and Sparky UI runs under root user within docker container, that allows things like installing system packages (`package-install`) and any other operations requiring privileged user,  through Sparky scenarios.  Just put 

```yaml
sparrowdo: 
  no_sudo: true
```
option in `sparky.yaml` configuration files.

* I use alpine OS base images, not alpine-raku as the last one installs Rakudo into none root user

**Comment by melezhik** [comment]
I pushed updated image to docker hub

**Comment by thibaultduponchelle** [comment]
Great! I will test it and give you feedback

**Comment by thibaultduponchelle** [comment]
The docker image is working fine

**Comment by JJ** [comment]
You can also simply slap USER root on top of the image if you want root privileges, or run it with --user=root.
